name: snap_video
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  collection: ^1.18.0
  sqflite: ^2.4.2+1
  path_provider: ^2.1.6
  path: ^1.9.1
  uuid: ^4.6.0
  intl: ^0.20.3
  dio: ^5.11.1
  http: ^1.6.0
  just_audio: ^0.10.6
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  video_player: ^2.11.1
  ffmpeg_kit_flutter_new: ^4.6.2
  youtube_explode_dart: ^3.1.0
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.0+3
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# Cấu hình tự động sinh icon ứng dụng BDSNAP
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#071B64"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#071B64" # Màu nền xanh than đậm đồng bộ với Icon
  image: assets/icon/app_icon.png
  android_12:
    image: assets/icon/app_icon.png
    icon_background_color: "#071B64"
  fullscreen: true